name: ua_debug_view
description: A fully customizable, modular Flutter debug panel. Plug in only the modules you need.
version: 1.0.0
homepage: https://github.com/useradgents/ua_debug_view
repository: https://github.com/useradgents/ua_debug_view
issue_tracker: https://github.com/useradgents/ua_debug_view/issues
topics:
  - debug
  - devtools
  - debugging
  - developer-tools
  - panel

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: '>=8.3.0 <11.0.0'
  shared_preferences: ^2.5.5
  sensors_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
